spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mapdb?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 2027
