spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mapdb?createDatabaseIfNotExist=true
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 2027
